name: Java CI

on:
  push:
    branches: [ angular-js-1.6.10 ]
  pull_request:
    branches: [ angular-js-1.6.10 ]

permissions:
  contents: read
  security-events: write

jobs:
  build-ptip-aggregate:
    name: Build Spring Pet Clinic with Java 8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B verify
